# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Sat Sep 10 19:19:12 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_caillasse(object):
    def setupUi(self, caillasse):
        caillasse.setObjectName(_fromUtf8("caillasse"))
        caillasse.resize(851, 600)
        self.centralwidget = QtGui.QWidget(caillasse)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setAccessibleName(_fromUtf8(""))
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.Persons = QtGui.QWidget()
        self.Persons.setObjectName(_fromUtf8("Persons"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Persons)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter_2 = QtGui.QSplitter(self.Persons)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.all_persons = QtGui.QTableView(self.splitter_2)
        self.all_persons.setAccessibleName(_fromUtf8(""))
        self.all_persons.setObjectName(_fromUtf8("all_persons"))
        self.all_persons.horizontalHeader().setVisible(True)
        self.one_person = QtGui.QTableView(self.splitter_2)
        self.one_person.setObjectName(_fromUtf8("one_person"))
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.tabs.addTab(self.Persons, _fromUtf8(""))
        self.Expenses = QtGui.QWidget()
        self.Expenses.setObjectName(_fromUtf8("Expenses"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Expenses)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtGui.QSplitter(self.Expenses)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.all_expenses = QtGui.QTableView(self.splitter)
        self.all_expenses.setObjectName(_fromUtf8("all_expenses"))
        self.one_expense = QtGui.QTableView(self.splitter)
        self.one_expense.setObjectName(_fromUtf8("one_expense"))
        self.verticalLayout_2.addWidget(self.splitter)
        self.tabs.addTab(self.Expenses, _fromUtf8(""))
        self.transfers = QtGui.QWidget()
        self.transfers.setObjectName(_fromUtf8("transfers"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.transfers)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.all_transfers = QtGui.QTableView(self.transfers)
        self.all_transfers.setObjectName(_fromUtf8("all_transfers"))
        self.verticalLayout_4.addWidget(self.all_transfers)
        self.tabs.addTab(self.transfers, _fromUtf8(""))
        self.advices = QtGui.QWidget()
        self.advices.setObjectName(_fromUtf8("advices"))
        self.tabs.addTab(self.advices, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabs)
        caillasse.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(caillasse)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuLoad = QtGui.QMenu(self.menubar)
        self.menuLoad.setObjectName(_fromUtf8("menuLoad"))
        self.menuItems = QtGui.QMenu(self.menubar)
        self.menuItems.setObjectName(_fromUtf8("menuItems"))
        caillasse.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(caillasse)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        caillasse.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(caillasse)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        caillasse.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(caillasse)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        caillasse.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionSave = QtGui.QAction(caillasse)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(caillasse)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionRecent = QtGui.QAction(caillasse)
        self.actionRecent.setObjectName(_fromUtf8("actionRecent"))
        self.actionSave_copy = QtGui.QAction(caillasse)
        self.actionSave_copy.setObjectName(_fromUtf8("actionSave_copy"))
        self.actionNew = QtGui.QAction(caillasse)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionNew_person = QtGui.QAction(caillasse)
        self.actionNew_person.setObjectName(_fromUtf8("actionNew_person"))
        self.actionNew_expense = QtGui.QAction(caillasse)
        self.actionNew_expense.setObjectName(_fromUtf8("actionNew_expense"))
        self.actionRemove_person = QtGui.QAction(caillasse)
        self.actionRemove_person.setObjectName(_fromUtf8("actionRemove_person"))
        self.actionRemove_expense = QtGui.QAction(caillasse)
        self.actionRemove_expense.setObjectName(_fromUtf8("actionRemove_expense"))
        self.actionNew_transfer = QtGui.QAction(caillasse)
        self.actionNew_transfer.setObjectName(_fromUtf8("actionNew_transfer"))
        self.actionRemove_transfer = QtGui.QAction(caillasse)
        self.actionRemove_transfer.setObjectName(_fromUtf8("actionRemove_transfer"))
        self.menuLoad.addAction(self.actionNew)
        self.menuLoad.addAction(self.actionSave)
        self.menuLoad.addAction(self.actionSave_copy)
        self.menuLoad.addAction(self.actionLoad)
        self.menuLoad.addAction(self.actionRecent)
        self.menuItems.addAction(self.actionNew_person)
        self.menuItems.addAction(self.actionNew_expense)
        self.menuItems.addSeparator()
        self.menuItems.addAction(self.actionRemove_person)
        self.menuItems.addAction(self.actionRemove_expense)
        self.menubar.addAction(self.menuLoad.menuAction())
        self.menubar.addAction(self.menuItems.menuAction())
        self.toolBar.addAction(self.actionRecent)
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSave_copy)
        self.toolBar_2.addAction(self.actionNew_person)
        self.toolBar_2.addAction(self.actionRemove_person)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.actionNew_expense)
        self.toolBar_2.addAction(self.actionRemove_expense)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.actionNew_transfer)
        self.toolBar_2.addAction(self.actionRemove_transfer)

        self.retranslateUi(caillasse)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(caillasse)

    def retranslateUi(self, caillasse):
        caillasse.setWindowTitle(QtGui.QApplication.translate("caillasse", "Caillasse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.Persons), QtGui.QApplication.translate("caillasse", "Persons", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.Expenses), QtGui.QApplication.translate("caillasse", "Expenses", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.transfers), QtGui.QApplication.translate("caillasse", "Transfers", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.advices), QtGui.QApplication.translate("caillasse", "Advices", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoad.setTitle(QtGui.QApplication.translate("caillasse", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItems.setTitle(QtGui.QApplication.translate("caillasse", "Items", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("caillasse", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_2.setWindowTitle(QtGui.QApplication.translate("caillasse", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("caillasse", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("caillasse", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("caillasse", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setShortcut(QtGui.QApplication.translate("caillasse", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecent.setText(QtGui.QApplication.translate("caillasse", "Recent", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_copy.setText(QtGui.QApplication.translate("caillasse", "Save a copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("caillasse", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("caillasse", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_person.setText(QtGui.QApplication.translate("caillasse", "New person", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_person.setShortcut(QtGui.QApplication.translate("caillasse", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_expense.setText(QtGui.QApplication.translate("caillasse", "New expense", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_expense.setToolTip(QtGui.QApplication.translate("caillasse", "New expense", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_expense.setShortcut(QtGui.QApplication.translate("caillasse", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_person.setText(QtGui.QApplication.translate("caillasse", "Remove person", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_expense.setText(QtGui.QApplication.translate("caillasse", "Remove expense", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_transfer.setText(QtGui.QApplication.translate("caillasse", "New transfer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_transfer.setShortcut(QtGui.QApplication.translate("caillasse", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_transfer.setText(QtGui.QApplication.translate("caillasse", "Remove transfer", None, QtGui.QApplication.UnicodeUTF8))

